version: "3.8"

services:

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n

    ports:
      - "5678:5678"

    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=tni12345
      - N8N_PORT=5678
      - N8N_HOST=saltish-forethoughtfully-laverna.ngrok-free.dev
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://saltish-forethoughtfully-laverna.ngrok-free.dev/
      - TZ=Asia/Bangkok
      - N8N_FILESYSTEM_ALLOWED_PATHS=/home/node/.n8n-files

    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_files:/home/node/.n8n-files

    restart: always


  dashboard:
    image: nginx:alpine
    container_name: customer-dashboard

    ports:
      - "8080:80"

    volumes:
      - ./dashboard/public:/usr/share/nginx/html:ro

    restart: always
